{{- if .Values.sedaiGrafanaAlloy.enabled }}
---
# Source: alloy/templates/controllers/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sedai-grafana-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    app.kubernetes.io/name: sedai-grafana-alloy
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: sedai-grafana-alloy
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: alloy
        checksum/config: d8548c34e1fb10f42234fba366be5c3749164d66bf10846bbe7da473a555662
      labels:
        app.kubernetes.io/name: sedai-grafana-alloy
        {{- with .Values.globalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.globalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: sedai-grafana-alloy

      {{- with .Values.sedaiGrafanaAlloy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or .Values.globalTolerations .Values.sedaiGrafanaAlloy.tolerations }}
      tolerations:
        {{- with .Values.globalTolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sedaiGrafanaAlloy.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- with .Values.sedaiGrafanaAlloy.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      containers:
        - name: alloy
          image: "{{ include "sedai-smart-agent.imageRepository" (dict "globalRegistry" .Values.globalRegistry "repository" .Values.image.grafanaAlloy.repository) }}:{{ .Values.image.grafanaAlloy.imageTag }}"
          imagePullPolicy: {{ .Values.image.grafanaAlloy.imagePullPolicy }}
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/tmp/alloy
            - --server.http.listen-addr=0.0.0.0:12345
            - --server.http.ui-path-prefix=/
            - --stability.level=generally-available
          env:
            - name: ALLOY_DEPLOY_MODE
              value: "helm"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 12345
              name: http-metrics
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 12345
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "{{ .Values.resources.grafanaAlloy.cpu.requests }}"
              memory: "{{ .Values.resources.grafanaAlloy.memory.requests }}"
            limits:
              cpu: "{{ .Values.resources.grafanaAlloy.cpu.limits }}"
              memory: "{{ .Values.resources.grafanaAlloy.memory.limits }}"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
        - name: config-reloader
          image: "{{ include "sedai-smart-agent.imageRepository" (dict "globalRegistry" .Values.globalRegistry "repository" .Values.image.reload.repository) }}:{{ .Values.image.reload.imageTag }}"
          args:
            - --watched-dir=/etc/alloy
            - --reload-url=http://localhost:12345/-/reload
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
      hostPID: true
      dnsPolicy: ClusterFirst
      volumes:
        - name: config
          configMap:
            name: sedai-grafana-alloy
{{- end }}
