{{- if .Values.smartAgentEnroll.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}"
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ .Values.workload.smartAgentEnroll.name }}
    spec:
      serviceAccountName: "{{ .Values.workload.smartAgentEnroll.name }}-sa"
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: sedai-enroll
          image: "{{ .Values.image.smartagentEnroll.repository }}:{{ .Values.image.smartagentEnroll.imageTag }}"
          command: ["/bin/sh", "-c", "python enroll_sedai.py"]
          imagePullPolicy: "{{ .Values.image.smartagentEnroll.imagePullPolicy }}"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: "{{ .Values.workload.smartAgentEnroll.name }}-secret"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault                                
{{- end }}