{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "sedai-kube-spec-controller-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app: "sedai-kube-spec-controller-db"
data:
    dbName: "c2VkYWlkYg=="
    dbUsername: "c2VkYWk="
    dbPassword: {{ derivePassword 1 "long" .Release.Namespace .Release.Name .Chart.Name | b64enc }}
{{- end }}