{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "sedai-kube-spec-controller-db-service"
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller-db"
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Values.namespace }}
  annotations:
spec:
  ports:
  - name: "sedai-db-port"
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: "sedai-kube-spec-controller-db"
  type: ClusterIP
{{- end }}