{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sedai-kube-spec-controller-pvc"
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller"
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.sedaiSync.storage | default "1Gi" }}
{{- end }}
