{{- if .Values.sedaiSync.enabled }}
{{- $ca := genCA "sedai-kube-spec-controller-ca" 3650 }}
{{- $cert := genSignedCert (printf "sedai-kube-spec-controller-svc.%s" .Values.namespace) (list) (list (printf "sedai-kube-spec-controller-svc.%s.svc" .Values.namespace)) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: sedai-kube-spec-controller-tls
  namespace: {{ .Values.namespace }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "sedai-kube-spec-controller-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller-db"
data:
    dbName: "c2VkYWlkYg=="
    dbUsername: "c2VkYWk="
    dbPassword: {{ derivePassword 1 "long" (.Release.Time | toString) .Release.Name .Chart.Name | b64enc }}
{{- end }}