{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "sedai-kube-spec-controller-secrets"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller-db"
data:
    dbName: "c2VkYWlkYg=="
    dbUsername: "c2VkYWk="
    dbPassword: {{ derivePassword 1 "long" (now | toString) .Release.Name .Chart.Name | b64enc }}
{{- end }}