{{- if .Values.sedaiSync.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sedai-kube-spec-controller-sa"
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.secretName }}
imagePullSecrets:
  - name: "{{ .Values.imagePullSecret.secretName }}"
{{- end }}
{{- end }}                 