{{- if and .Values.sedaiSync.enabled .Values.sedaiSync.db.enabled }}
{{- if not .Values.sedaiSync.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "sedai-kube-spec-controller-db"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller-db"
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.sedaiSync.db.user }}"
  POSTGRES_PASSWORD: "{{ .Values.sedaiSync.db.password }}"
  POSTGRES_DB: "{{ .Values.sedaiSync.db.name }}"
{{- end }}
{{- end }}
