{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "sedai-kube-spec-controller-svc"
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller"
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "api"
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: "sedai-kube-spec-controller"
  type: ClusterIP
{{- end }}