{{- if .Values.sedaiSync.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sedai-kube-spec-controller-dbclaim"
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    app: "sedai-kube-spec-controller-db"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}