{{- if .Values.sedaiSync.enabled }}
{{- $ca := genCA "sedai-kube-spec-controller-ca" 3650 }}
{{- $cert := genSignedCert (printf "sedai-kube-spec-controller-svc.%s" .Release.Namespace) (list) (list (printf "sedai-kube-spec-controller-svc.%s.svc" .Release.Namespace)) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: sedai-kube-spec-controller-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
type: kubernetes.io/tls

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sedai-kube-spec-controller-mutation-webhook
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: sedai-kube-spec-controller-svc.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: sedai-kube-spec-controller-svc
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 8443
      caBundle: {{ $ca.Cert | b64enc }}
    rules:
      - apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["deployments", "statefulsets", "daemonsets", "pods"]
    failurePolicy: 'Ignore'
    namespaceSelector:
      matchExpressions:
        - key: "kubernetes.io/metadata.name"  # Use the `metadata.name` of the namespace
          operator: NotIn
          values: ["{{ .Release.Namespace }}"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 1
{{- end }}