{{- if .Values.sedaiSync.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sedai-kube-spec-controller-db-sa"
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

{{- end }}                 