{{- if .Values.workload.sedaiPrometheus.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }} 
  name: "{{ .Values.workload.sedaiPrometheus.name }}-service"
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: sedai-prometheus-server
  sessionAffinity: None
  type: "ClusterIP"

{{- end }}