{{- if .Values.workload.sedaiPrometheus.enabled }}

---
# Source: sedai-smart-agent-chart/charts/sedai-prometheus/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }} 
  name: "{{ .Values.workload.sedaiPrometheus.name }}-pvc"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.sedaiPrometheus.storage }}"  

{{- end }}