{{- if .Values.workload.sedaiPrometheus.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }} 
  name: "{{ .Values.workload.sedaiPrometheus.name }}-sa"
  namespace: {{ .Values.namespace }}
  annotations:
    {}

{{- end }}