{{- if .Values.sedaiPrometheus.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: "{{ .Values.workload.prometheus.name }}-sa"
  namespace: {{ .Values.namespace }}
  annotations:
    {}
{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.secretName }}
imagePullSecrets:
  - name: "{{ .Values.imagePullSecret.secretName }}"
{{- end }}

{{- end }}