{{- if .Values.sedaiPrometheus.enabled }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: "{{ .Values.workload.prometheus.name }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  allow-snippet-annotations: "false"
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
      - /etc/config/rules
      - /etc/config/alerts
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
        metric_relabel_configs:
          - action: keep
            regex: prometheus_build_info|prometheus_config_last_reload_success_timestamp_seconds|prometheus_ready
            source_labels: [__name__]
      - job_name: kubernetes-apiservers
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            regex: default;kubernetes;https
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        metric_relabel_configs:
          - action: keep
            regex: kubernetes_build_info|kubernetes_feature_enabled
            source_labels: [__name__]
      - job_name: kubernetes-nodes
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - replacement: kubernetes.default.svc:443
            target_label: __address__
          - regex: (.+)
            replacement: /api/v1/nodes/$1/proxy/metrics
            source_labels:
              - __meta_kubernetes_node_name
            target_label: __metrics_path__
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        metric_relabel_configs:
          - action: keep
            regex: kubelet_active_pods|kubelet_desired_pods|kubelet_mirror_pods|kubelet_node_name|kubelet_managed_ephemeral_containers|kubelet_restarted_pods_total|kubelet_running_containers|kubelet_started_containers_total|kubelet_started_pods_errors_total|kubelet_started_pods_total|kubelet_evictions
            source_labels: [__name__]
      - job_name: kubernetes-nodes-cadvisor
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - replacement: kubernetes.default.svc:443
            target_label: __address__
          - regex: (.+)
            replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
            source_labels:
              - __meta_kubernetes_node_name
            target_label: __metrics_path__
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        metric_relabel_configs:
          - action: keep
            regex: container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_cfs_throttled_seconds_total|container_cpu_system_seconds_total|container_cpu_usage_seconds_total|container_cpu_user_seconds_total|container_fs_io_time_seconds_total|container_fs_io_time_weighted_seconds_total|container_memory_cache|container_memory_failcnt|container_memory_failures_total|container_memory_max_usage_bytes|container_memory_rss|container_memory_swap|container_memory_total_active_file_bytes|container_memory_total_inactive_file_bytes|container_memory_usage_bytes|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_receive_errors_total|container_network_receive_packets_dropped_total|container_network_transmit_bytes_total|container_network_transmit_errors_total|container_network_receive_packets_total|container_network_transmit_packets_dropped_total|container_network_transmit_packets_total|container_oom_events_total|container_sockets|container_processes|container_spec_cpu_period|container_spec_cpu_quota|container_spec_memory_limit_bytes|container_threads|container_threads_max
            source_labels: [__name__]
      - job_name: kubernetes-service-endpoints
        honor_labels: true
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            regex: true
            source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape
          - action: drop
            regex: true
            source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
          - action: replace
            regex: (https?)
            source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: (.+?)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels:
              - __address__
              - __meta_kubernetes_service_annotation_prometheus_io_port
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_service_name
            target_label: service
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node
        metric_relabel_configs:
          - action: keep
            regex: node_disk_info|node_dmi_info|node_load1|node_load15|node_load5|node_memory_MemAvailable_bytes|node_memory_MemFree_bytes|node_memory_MemTotal_bytes|node_netstat_Ip6_InOctets|node_netstat_Ip6_OutOctets|node_netstat_IpExt_InOctets|node_netstat_IpExt_OutOctets|node_network_receive_bytes_total|node_network_receive_packets_total|node_network_receive_drop_total|node_network_receive_errs_total|node_network_transmit_bytes_total|node_network_transmit_drop_total|node_network_transmit_errs_total|node_network_transmit_packets_total|node_os_info|node_selinux_config_mode|process_network_receive_bytes_total|process_network_transmit_bytes_total|kube_daemonset_metadata_generation|kube_daemonset_status_current_number_scheduled|kube_daemonset_status_desired_number_scheduled|kube_daemonset_status_number_available|kube_daemonset_status_number_misscheduled|kube_daemonset_status_number_ready|kube_daemonset_status_number_unavailable|kube_deployment_metadata_generation|kube_deployment_status_observed_generation|kube_deployment_created|kube_deployment_status_replicas|kube_deployment_status_replicas_ready|kube_deployment_status_replicas_available|kube_deployment_status_replicas_unavailable|kube_deployment_status_replicas_updated|kube_horizontalpodautoscaler_info|kube_horizontalpodautoscaler_metadata_generation|kube_horizontalpodautoscaler_spec_max_replicas|kube_horizontalpodautoscaler_spec_min_replicas|kube_horizontalpodautoscaler_spec_target_metric|kube_horizontalpodautoscaler_status_current_replicas|kube_horizontalpodautoscaler_status_desired_replicas|kube_horizontalpodautoscaler_status_condition|kube_ingress_info|kube_ingress_metadata_resource_version|kube_ingress_path|kube_job_info|kube_job_spec_parallelism|kube_job_spec_completions|kube_job_status_succeeded|kube_job_status_failed|kube_job_status_active|kube_job_complete|kube_job_status_start_time|kube_job_status_completion_time|kube_job_owner|kube_lease_owner|kube_mutatingwebhookconfiguration_info|kube_mutatingwebhookconfiguration_created|kube_mutatingwebhookconfiguration_metadata_resource_version|kube_node_info|kube_node_spec_taint|kube_node_spec_unschedulable|kube_node_status_allocatable|kube_node_status_capacity|kube_persistentvolumeclaim_info|kube_persistentvolumeclaim_status_phase|kube_persistentvolumeclaim_resource_requests_storage_bytes|kube_persistentvolumeclaim_access_mode|kube_persistentvolume_claim_ref|kube_persistentvolume_status_phase|kube_persistentvolume_info|kube_persistentvolume_capacity_bytes|kube_persistentvolume_volume_mode|kube_poddisruptionbudget_created|kube_poddisruptionbudget_status_current_healthy|kube_poddisruptionbudget_status_desired_healthy|kube_poddisruptionbudget_status_pod_disruptions_allowed|kube_poddisruptionbudget_status_expected_pods|kube_pod_container_info|kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_container_state_started|kube_pod_container_status_last_terminated_reason|kube_pod_container_status_last_terminated_exitcode|kube_pod_container_status_last_terminated_timestamp|kube_pod_container_status_restarts_total|kube_pod_container_status_running|kube_pod_container_status_terminated|kube_pod_container_status_terminated_reason|kube_pod_container_status_waiting|kube_pod_container_status_waiting_reason|kube_pod_info|kube_pod_init_container_info|kube_pod_init_container_resource_limits|kube_pod_init_container_resource_requests|kube_pod_init_container_status_ready|kube_pod_init_container_status_restarts_total|kube_pod_init_container_status_terminated_reason|kube_pod_init_container_status_waiting|kube_pod_init_container_status_waiting_reason|kube_pod_status_qos_class|kube_pod_tolerations|kube_pod_service_account|kube_pod_scheduler|kube_pod_start_time|kube_pod_status_phase|kube_pod_status_ready_time|kube_pod_status_scheduled_time|kube_replicaset_created|kube_replicaset_spec_replicas|kube_replicaset_metadata_generation|kube_replicaset_owner|kube_service_info|kube_service_spec_type|kube_service_status_load_balancer_ingress|kube_statefulset_created|kube_statefulset_status_replicas|kube_statefulset_status_replicas_available|kube_statefulset_status_replicas_current|kube_statefulset_status_replicas_ready|kube_statefulset_status_replicas_updated|kube_statefulset_replicas|kube_statefulset_metadata_generation|kube_statefulset_persistentvolumeclaim_retention_policy|kube_statefulset_status_current_revision|kube_statefulset_status_update_revision|kube_storageclass_info|kube_validatingwebhookconfiguration_info|kube_validatingwebhookconfiguration_metadata_resource_version|kube_validatingwebhookconfiguration_webhook_clientconfig_service|kube_volumeattachment_labels|kube_volumeattachment_info|kube_volumeattachment_spec_source_persistentvolume|kube_volumeattachment_status_attached|kube_volumeattachment_status_attachment_metadata|node_cpu_guest_seconds_total|node_cpu_seconds_total|node_disk_io_time_seconds_total|node_disk_io_time_weighted_seconds_total|node_disk_read_bytes_total|node_disk_read_time_seconds_total|node_disk_writes_bytes_total|node_disk_write_time_seconds_total|istio_requests_total|istio_request_duration_milliseconds_count|istio_request_duration_milliseconds_sum|istio_request_duration_milliseconds_bucket|nginx_ingress_controller_requests|nginx_ingress_controller_request_duration_seconds_count|nginx_ingress_controller_request_duration_seconds_sum|envoy_cluster_upstream_rq_time|envoy_cluster_upstream_rq_completed|traefik_service_requests_total|traefik_service_request_duration_seconds
            source_labels: [__name__]
      - job_name: kubernetes-pods
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            regex: true
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
          - action: drop
            regex: true
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
          - action: replace
            regex: (https?)
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scheme
            target_label: __scheme__
          - action: replace
            regex: (.+)
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
          - action: replace
            regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
            replacement: '[$2]:$1'
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              - __meta_kubernetes_pod_ip
            target_label: __address__
          - action: replace
            regex: (\d+);((([0-9]+?)(\.|$)){4})
            replacement: $2:$1
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              - __meta_kubernetes_pod_ip
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: drop
            regex: Pending|Succeeded|Failed|Completed
            source_labels:
              - __meta_kubernetes_pod_phase
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node
        metric_relabel_configs:
          - action: keep
            regex: beyla_network_flow_bytes_total|istio_requests_total|istio_request_duration_milliseconds_count|istio_request_duration_milliseconds_sum|istio_request_duration_milliseconds_bucket|nginx_ingress_controller_requests|nginx_ingress_controller_request_duration_seconds_count|nginx_ingress_controller_request_duration_seconds_sum|envoy_cluster_upstream_rq_time|envoy_cluster_upstream_rq_completed|traefik_service_requests_total|traefik_service_request_duration_seconds
            source_labels: [__name__]
  recording_rules.yml: |
    {}
  rules: |
    {}

{{- end }}
