{{- if .Values.sedaiIntegrationSettings.rbacReadOnly }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.workload.smartAgent.name }}-cluster-role"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - services
  - pods
  - nodes
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - deployments/scale 
  - statefulsets/scale  
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - autoscaling
  - autoscaling.k8s.io 
  resources:
  - horizontalpodautoscalers
  - verticalpodautoscalers
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - ingressclasses
  - networkpolicies
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.k8s.aws
  - karpenter.sh
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - kubeflow.org
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- verbs:
  - get
  nonResourceURLs:
  - /metrics
{{- end }}