{{- if .Values.sedaiGrafanaAlloy.enabled }}
---
# Source: victoria-metrics-single/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/name: sedai-victoria-metrics
    app.kubernetes.io/component: networking
    app: server
  name: sedai-victoria-metrics-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: sedai-victoria-metrics
    app: server
{{- end }}
