{{- if or .Values.sedaiGrafanaAlloy.enabled .Values.sedaiVictoriaMetrics.enabled }}
---
# Source: victoria-metrics-single/templates/serviceaccount.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    app.kubernetes.io/name: sedai-victoria-metrics
    app.kubernetes.io/component: rbac
  name: sedai-victoria-metrics-server
  namespace: {{ .Release.Namespace }}
{{- end }}
