{{- if or .Values.sedaiGrafanaAlloy.enabled .Values.sedaiVictoriaMetrics.enabled }}
{{ include "sedai-smart-agent.persistentVolume" (dict
     "root" .
     "name" (printf "%s-pv-%s" .Values.workload.victoriaMetrics.name .Release.Namespace)
     "pv" .Values.sedaiVictoriaMetrics.persistentVolume
     "storageClass" .Values.sedaiVictoriaMetrics.storageClass
     "defaultCapacity" .Values.resources.victoriaMetrics.storage
   ) }}
{{- end }}
