{{- if .Values.sedaiBeyla.enabled }}
---
# Source: beyla/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sedai-beyla
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }} 
data:
  beyla-config.yml: |
    discovery:
      services:
        - k8s_namespace: .
      exclude_services:
        - exe_path: ".*alloy.*|.*otelcol.*|.*beyla.*"
    attributes:
      kubernetes:
        enable: true
      select:
        beyla_network_flow_bytes:
          include:
          - transport
          - src_address
          - dst_address
          - src_name
          - dst_name
          - k8s_src_name
          - k8s_dst_name
          - k8s_src_namespace
          - k8s_dst_namespace
          - k8s_src_owner_name
          - k8s_dst_owner_name
          - k8s_src_owner_type
          - k8s_dst_owner_type
          - k8s_cluster_name
          - src.zone
          - dst.zone
    filter:
      network:
        k8s_dst_owner_name:
          not_match: '{kube*,*jaeger-agent*,*prometheus*,*promtail*,*grafana-agent*}'
        k8s_src_owner_name:
          not_match: '{kube*,*jaeger-agent*,*prometheus*,*promtail*,*grafana-agent*}'
    network:
      enable: true
    prometheus_export:
      features:
      - application
      - network
      path: /metrics
      port: 8080
{{- end }}