{{- if .Values.sedaiBeyla.enabled }}
---
# Source: beyla/templates/daemon-set.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sedai-beyla
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sedai-beyla
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sedai-beyla
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8999"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: sedai-beyla
        {{- with .Values.globalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.globalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: sedai-beyla
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      {{- with .Values.sedaiBeyla.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or .Values.globalTolerations .Values.sedaiBeyla.tolerations }}
      tolerations:
        {{- with .Values.globalTolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sedaiBeyla.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      containers:
        - name: beyla
          image: "{{ .Values.globalRegistry }}/{{ .Values.image.beyla.repository }}:{{ .Values.image.beyla.imageTag }}"
          imagePullPolicy: "{{ .Values.image.beyla.imagePullPolicy }}"
          securityContext:
            privileged: true
          ports:
          - name: metrics
            containerPort: 8999
            protocol: TCP
          resources:
            requests:
              cpu: "{{ .Values.resources.sedaiBeyla.cpu.requests }}"          
              memory: "{{ .Values.resources.sedaiBeyla.memory.requests }}"
            limits:
              cpu: "{{ .Values.resources.sedaiBeyla.cpu.limits }}"
              memory: "{{ .Values.resources.sedaiBeyla.memory.limits }}"
          env:
            - name: BEYLA_CONFIG_PATH
              value: "/etc/beyla/config/beyla-config.yml"
          volumeMounts:
            - mountPath: /etc/beyla/config
              name: beyla-config
      volumes:
        - name: beyla-config
          configMap:
            name: sedai-beyla
{{- end }}