{{- if .Values.workload.sedaiNodeExporter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.workload.sedaiNodeExporter.name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: sedai-prometheus-node-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: sedai-prometheus-node-exporter
{{- end }}  