# Example: GCP Monitoring with Service Account Key via Values (NOT RECOMMENDED FOR PRODUCTION)
# This example shows how to configure GCP monitoring by providing the service account key directly in values

sedaiIntegrationSettings:
  clusterName: "my-gcp-cluster"
  sedaiApiToken: "your-api-token"
  sedaiBaseUrl: "https://app.sedai.io"
  clusterProvider: "GCP"

monitoringProvider:
  gcpMonitoring:
    enabled: true
    projectID: "my-gcp-project-123"
    # Service account key JSON directly in values (NOT recommended for production)
    # This can be formatted for readability - Helm will compact it automatically
    serviceAccountKeyJson: |
      {
        "type": "service_account",
        "project_id": "my-gcp-project-123",
        "private_key_id": "abc123...",
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...\n-----END PRIVATE KEY-----\n",
        "client_email": "my-service-account@my-gcp-project-123.iam.gserviceaccount.com",
        "client_id": "123456789012345678901",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/my-service-account%40my-gcp-project-123.iam.gserviceaccount.com"
      }

# Enable Smart Agent components
smartAgentEnroll:
  enabled: true

sedaiPrometheus:
  enabled: true

sedaiKSM:
  enabled: true