# Example: GCP Monitoring with Service Account Key via Secret
# This example shows how to configure GCP monitoring using a service account key stored in a Kubernetes secret

sedaiIntegrationSettings:
  clusterName: "my-gcp-cluster"
  sedaiApiToken: "your-api-token"
  sedaiBaseUrl: "https://app.sedai.io"
  clusterProvider: "GCP"

monitoringProvider:
  gcpMonitoring:
    enabled: true
    projectID: "my-gcp-project-123"
    # Reference to existing Kubernetes secret containing service account key
    gcpSecret: "gcp-service-account-secret"
    gcpServiceAccountKeySecretKey: "key.json"  # Optional, defaults to "key.json"

# Enable Smart Agent components
smartAgentEnroll:
  enabled: true

sedaiPrometheus:
  enabled: true

sedaiKSM:
  enabled: true

---
# Create this secret beforehand with your service account key:
# kubectl create secret generic gcp-service-account-secret \
#   --from-file=key.json=path/to/your/service-account-key.json \
#   --namespace=sedai-smart-agent