{{- if .Values.smartAgentEnroll.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}"
  namespace: {{ .Release.Namespace }}
  {{- if or .Values.globalAnnotations .Values.smartAgentEnroll.jobAnnotations }}
  annotations:
    {{- with .Values.globalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- range $key, $value := .Values.smartAgentEnroll.jobAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ .Values.workload.smartAgentEnroll.name }}
        {{- with .Values.globalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.globalAnnotations .Values.smartAgentEnroll.podAnnotations }}
      annotations:
        {{- with .Values.globalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- range $key, $value := .Values.smartAgentEnroll.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: "{{ .Values.workload.smartAgentEnroll.name }}-sa"
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      {{- with .Values.smartAgentEnroll.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or .Values.globalTolerations .Values.smartAgentEnroll.tolerations }}
      tolerations:
        {{- with .Values.globalTolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.smartAgentEnroll.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- with .Values.smartAgentEnroll.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      containers:
        - name: sedai-enroll
          image: "{{ include "sedai-smart-agent.imageRepository" (dict "globalRegistry" .Values.globalRegistry "repository" .Values.image.smartagentEnroll.repository) }}:{{ .Values.image.smartagentEnroll.imageTag }}"
          command: ["/bin/sh", "-c", "python enroll_sedai.py"]
          imagePullPolicy: "{{ .Values.image.smartagentEnroll.imagePullPolicy }}"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if and .Values.sedaiIntegrationSettings.sedaiApiTokenSecret .Values.sedaiIntegrationSettings.sedaiApiTokenSecretKey }}
            - name: SEDAI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sedaiIntegrationSettings.sedaiApiTokenSecret }}
                  key: {{ .Values.sedaiIntegrationSettings.sedaiApiTokenSecretKey }}
            {{- end }}
            {{- if and .Values.monitoringProvider.datadog.datadogSecret .Values.monitoringProvider.datadog.datadogApiKeySecretKey .Values.monitoringProvider.datadog.datadogApplicationKeySecretKey }}
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.monitoringProvider.datadog.datadogSecret }}
                  key: {{ .Values.monitoringProvider.datadog.datadogApiKeySecretKey }}
            - name: DATADOG_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.monitoringProvider.datadog.datadogSecret }}
                  key: {{ .Values.monitoringProvider.datadog.datadogApplicationKeySecretKey }}
            {{- end }}                  
          envFrom:
            - secretRef:
                name: "{{ .Values.workload.smartAgentEnroll.name }}-secret"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault                                
{{- end }}
