{{- if and .Values.smartAgentEnroll.enabled .Values.smartAgentEnroll.clearDuplicateAgents.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-duplicate-check-sa"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
  {{- else }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
  {{- end }}
{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.secretName }}
imagePullSecrets:
  - name: "{{ .Values.imagePullSecret.secretName }}"
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-duplicate-check-role"
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
  {{- else }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
  {{- end }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["list", "delete"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-duplicate-check-binding"
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
  {{- else }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.workload.smartAgentEnroll.name }}-duplicate-check-sa"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.workload.smartAgentEnroll.name }}-duplicate-check-role"
  apiGroup: rbac.authorization.k8s.io

{{- end }}
