{{- if .Values.smartAgentEnroll.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-role-binding"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.workload.smartAgentEnroll.name }}-sa"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Values.workload.smartAgentEnroll.name }}-role"
  apiGroup: rbac.authorization.k8s.io

{{- end }}                 