{{- if .Values.smartAgentEnroll.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-post-upgrade"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Values.workload.smartAgentEnroll.name }}-post-upgrade
        {{- with .Values.globalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.globalAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: "{{ .Values.workload.smartAgentEnroll.name }}-sa"
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      {{- with .Values.smartAgentEnroll.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- if or .Values.globalTolerations .Values.smartAgentEnroll.tolerations }}
      tolerations:
        {{- with .Values.globalTolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.smartAgentEnroll.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}

      {{- with .Values.smartAgentEnroll.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      containers:
        - name: sedai-post-install
          image: "{{ include "sedai-smart-agent.imageRepository" (dict "globalRegistry" .Values.globalRegistry "repository" .Values.image.smartagentEnroll.repository) }}:{{ .Values.image.smartagentEnroll.imageTag }}"
          command: ["/bin/sh", "-c", "python complete_sedai.py"]
          imagePullPolicy: "{{ .Values.image.smartagentEnroll.imagePullPolicy }}"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if and .Values.sedaiIntegrationSettings.sedaiApiTokenSecret .Values.sedaiIntegrationSettings.sedaiApiTokenSecretKey }}
            - name: SEDAI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sedaiIntegrationSettings.sedaiApiTokenSecret }}
                  key: {{ .Values.sedaiIntegrationSettings.sedaiApiTokenSecretKey }}
            {{- end }}
            {{- if and .Values.monitoringProvider.datadog.datadogSecret .Values.monitoringProvider.datadog.datadogApiKeySecretKey .Values.monitoringProvider.datadog.datadogApplicationKeySecretKey }}
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.monitoringProvider.datadog.datadogSecret }}
                  key: {{ .Values.monitoringProvider.datadog.datadogApiKeySecretKey }}
            - name: DATADOG_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.monitoringProvider.datadog.datadogSecret }}
                  key: {{ .Values.monitoringProvider.datadog.datadogApplicationKeySecretKey }}
            {{- end }}                  
          envFrom:
            - secretRef:
                name: "{{ .Values.workload.smartAgentEnroll.name }}-secret"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
{{- end }}