{{- if and .Values.smartAgentEnroll.enabled .Values.smartAgentEnroll.clearDuplicateAgents.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-duplicate-check-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
    {{- toYaml .Values.globalAnnotations | nindent 4 }}
  {{- else }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-1"
  {{- end }}
type: Opaque
stringData:
  SEDAI_BASE_URL: {{ .Values.sedaiIntegrationSettings.sedaiBaseUrl }}
  {{- if .Values.sedaiIntegrationSettings.sedaiApiToken }}
  SEDAI_API_TOKEN: {{ .Values.sedaiIntegrationSettings.sedaiApiToken }}
  {{- end }}
  CLUSTER_NAME: {{ .Values.sedaiIntegrationSettings.clusterName }}
  NICK_NAME: {{ .Values.sedaiIntegrationSettings.nickName }}
  {{- if or .Values.sedaiPrometheus.enabled .Values.monitoringProvider.sedaiManagedPrometheus.enabled }}
  SEDAI_PROMETHEUS_ENDPOINT: "http://{{ .Values.workload.prometheus.name }}-service"
  {{- end }}
{{- end }}
