{{- if and .Values.smartAgentEnroll.enabled .Values.sedaiIntegrationSettings.enableDeRegisterJob }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-deregister-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "-1"
    {{- with .Values.globalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  SEDAI_BASE_URL: {{ .Values.sedaiIntegrationSettings.sedaiBaseUrl }}
  {{- if .Values.sedaiIntegrationSettings.sedaiApiToken }}
  SEDAI_API_TOKEN: {{ .Values.sedaiIntegrationSettings.sedaiApiToken }}
  {{- end }}
  CLUSTER_PROVIDER: {{ .Values.sedaiIntegrationSettings.clusterProvider }}
  CLUSTER_NAME: {{ .Values.sedaiIntegrationSettings.clusterName }}
  NICK_NAME: {{ .Values.sedaiIntegrationSettings.nickName }}

  {{- if .Values.proxySettings.enabled }}
  PROXY_HOST: "{{ .Values.proxySettings.proxyHost }}"      
  PROXY_PORT: "{{ .Values.proxySettings.proxyPort }}"      
  PROXY_USERNAME: "{{ .Values.proxySettings.proxyUsername }}"      
  PROXY_PASSWORD: "{{ .Values.proxySettings.proxyPassword }}"    
  {{- end }}
  
  FORCE_CREATE: "{{ .Values.sedaiIntegrationSettings.forceCreate }}"

{{- end }}