{{- if .Values.smartAgentEnroll.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-sa"
  namespace: {{ .Values.namespace }}

{{- end }}                 