{{- if .Values.workload.smartAgentEnroll.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-role"
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "update", "delete"]

{{- end }}