{{- if and .Values.smartAgentEnroll.enabled .Values.sedaiIntegrationSettings.enableDeRegisterJob }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.workload.smartAgentEnroll.name }}-deregister"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.globalAnnotations .Values.smartAgentEnroll.deregisterJobAnnotations }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "1"
    {{- with .Values.globalAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- range $key, $value := .Values.smartAgentEnroll.deregisterJobAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "1"
  {{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ .Values.workload.smartAgentEnroll.name }}
        {{- with .Values.globalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.globalAnnotations .Values.smartAgentEnroll.deregisterPodAnnotations }}
      annotations:
        {{- with .Values.globalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- range $key, $value := .Values.smartAgentEnroll.deregisterPodAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: "{{ .Values.workload.smartAgentEnroll.name }}-deregister-sa"
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - name: sedai-deregister
          image: "{{ include "sedai-smart-agent.imageRepository" (dict "globalRegistry" .Values.globalRegistry "repository" .Values.image.smartagentEnroll.repository) }}:{{ .Values.image.smartagentEnroll.imageTag }}"
          command: ["/bin/sh", "-c", "python deregister_sedai_api.py"]
          imagePullPolicy: "{{ .Values.image.smartagentEnroll.imagePullPolicy }}"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if and .Values.sedaiIntegrationSettings.sedaiApiTokenSecret .Values.sedaiIntegrationSettings.sedaiApiTokenSecretKey }}
            - name: SEDAI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sedaiIntegrationSettings.sedaiApiTokenSecret }}
                  key: {{ .Values.sedaiIntegrationSettings.sedaiApiTokenSecretKey }}
            {{- end }}
          envFrom:
            - secretRef:
                name: "{{ .Values.workload.smartAgentEnroll.name }}-deregister-secret"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
{{- end }}
