{{- if .Values.workload.sedaiKSM.enabled }}

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.workload.sedaiKSM.name }}-service"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: sedai-kube-state-metrics

{{- end }}
