{{- if or .Values.sedaiGrafanaAlloy.enabled .Values.sedaiKSM.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:    
    {{- include "sedai-smart-agent.labels" . | nindent 4 }} 
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: "{{ .Values.workload.ksm.name }}-sa"
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.secretName }}
imagePullSecrets:
  - name: "{{ .Values.imagePullSecret.secretName }}"
  
{{- end }}
{{- end }}
