{{- if .Values.workload.sedaiKSM.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:    
    {{- include "sedai-smart-agent.labels" . | nindent 4 }} 
  name: "{{ .Values.workload.sedaiKSM.name }}-sa"
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true

{{- end }}