{{- if .Values.workload.sedaiKSM.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.workload.sedaiKSM.name }}-cluster-role-binding"
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.workload.sedaiKSM.name }}-cluster-role"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.workload.sedaiKSM.name }}-sa"
    namespace: {{ .Values.namespace }}

{{- end }}