{{- if or .Values.sedaiGrafanaAlloy.enabled .Values.sedaiKSM.enabled }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.workload.ksm.name }}-cluster-role-binding"
  labels:
    {{- include "sedai-smart-agent.labels" . | nindent 4 }}
    {{- with .Values.globalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.globalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Values.workload.ksm.name }}-cluster-role"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.workload.ksm.name }}-sa"
    namespace: {{ .Values.namespace }}

{{- end }}