{{- if and .Values.sedaiSmartScheduler.enabled .Values.sedaiSmartScheduler.logForwarder.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sedai-smart-scheduler-loki-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smart-scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  LOKI_HOST: {{ .Values.sedaiSmartScheduler.logForwarder.loki.host | quote }}
  LOKI_PORT: {{ .Values.sedaiSmartScheduler.logForwarder.loki.port | quote }}
  LOKI_USERNAME: {{ .Values.sedaiSmartScheduler.logForwarder.loki.username | quote }}
  LOKI_PASSWORD: {{ .Values.sedaiSmartScheduler.logForwarder.loki.password | quote }}
{{- end }}
